### ISSUE TITLE
lauoyt problem on small screen

### ISSUE THREAD

**Issue by MparkG** [LeddaZ/ReVancedUpdater#10]
See pic, sony xyz1 compact
![Screenshot_20230517-125753](https://github.com/LeddaZ/ReVancedUpdater/assets/26872340/b9355f48-4830-4ee3-a69e-55a21accf5df)

thx

**Comment by MparkG** [comment]
Thx for the change Ledda
It did not quite fix it though; see clip

https://github.com/LeddaZ/ReVancedUpdater/assets/26872340/15789ec3-2100-4001-acf6-58eb1f3d4164


bottom bar is still blocking the view, problem appearently was not only that it is not scrollable.
thx!

**Comment by LeddaZ** [comment]
The latest update should have fixed this once and for all
