### ISSUE TITLE
Ui ideas?? 

### ISSUE THREAD

**Issue by MarshMeadow** [LeddaZ/ReVancedUpdater#26]
![Screenshot_20240210-020805_Vanced Manager.png](https://github.com/LeddaZ/ReVancedUpdater/assets/88599122/acd1b192-0aca-4354-8bb5-5cccb4769cfd)

![Screenshot_20240210-020810_Vanced Manager.png](https://github.com/LeddaZ/ReVancedUpdater/assets/88599122/c23e2e9a-e6ec-4618-94b9-bfe02ffb432e)

**Comment by LeddaZ** [comment]
I think the current UI is fine, I don't need more features and copying an already existing app isn't a good idea
