### ISSUE TITLE
What is x.apk?? 

### ISSUE THREAD

**Issue by MarshMeadow** [LeddaZ/ReVancedUpdater#36]
That modded Twitter?? []()![Screenshot_20240421-110836_ReVanced Updater.png](https://github.com/LeddaZ/ReVancedUpdater/assets/88599122/9a88f2e8-5333-4fdf-8df6-0830b3534bd5)

**Comment by dwaris** [comment]
Sadly yes. Nobody should be using Twitter anymore.
So can we just revert adding "X" (it's Twitter ffs), thanks.
![rnc3013ZL3Kf4VFk9lynBZXaV10Zw23OWqmd6xkM](https://github.com/LeddaZ/ReVancedUpdater/assets/12817063/8c462e26-4593-4307-b219-b7837f718e8b)

**Comment by LeddaZ** [comment]
> Sadly yes. Nobody should be using Twitter anymore. So can we just revert adding "X" (it's Twitter ffs), thanks. ![rnc3013ZL3Kf4VFk9lynBZXaV10Zw23OWqmd6xkM](https://private-user-images.githubusercontent.com/12817063/324903103-8c462e26-4593-4307-b219-b7837f718e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODk3NTQsIm5iZiI6MTcxMzg4OTQ1NCwicGF0aCI6Ii8xMjgxNzA2My8zMjQ5MDMxMDMtOGM0NjJlMjYtNDU5My00MzA3LWIyMTktYjc4MzdmNzE4ZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE2MjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNWNlNDBiMzY0OTZlNTZhN2Q0ZjVhMzM2NzMxNTI4NDBkY2Y2OWI0MTg2MjQ5ZDJmZGY2MzU4MGQ2Zjc2NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PneAg2O5MKL3E-HAwYRHdcxsJrDdbImpk0EM0r8snQM)

No one is forcing you to download Twitter, nor should you force your opinions on it on others. I made the app mainly for myself and I use Twitter whether you like it or not, if it bothers you that much you can fork the app and remove all Twitter/X related stuff.
