### ISSUE TITLE
Malware Infected app

### ISSUE THREAD

**Issue by DaniJetski** [LeddaZ/ReVancedUpdater#41]
I have 2 smartphones that have identified Revanced Updater as malware or infected app.

### Threats:
Virus name: APK:RepMalware [Trj]||arep
Danger level: High

**Comment by LeddaZ** [comment]
This app has no malware, you can check the source code yourself to confirm it. Whatever you're using to scan the app is detecting a false positive.

**Comment by DaniJetski** [comment]
I trust the code, I have only reported it to you so that you know that Avast and Sophos  have identified the 3.4.0 version as malware. I have updated to the latest version 3.4.1 and the alert has disappeared. Thank you!

**Comment by LeddaZ** [comment]
I see, maybe there was a vulnerability in some library that was updated with 3.4.1, thanks
