### ISSUE TITLE
In Updater 1.4.1 YT Vanced Music can no longer be downloaded!

### ISSUE THREAD

**Issue by rainman74** [LeddaZ/ReVancedUpdater#6]
In the Updater 1.4.1 YT Vanced Music can no longer be downloaded for about 2 days!

**Comment by rainman74** [comment]
Yes, I am sure, it's not my device as YouTube Revanced can be downloaded without errors.

Could it be that it is due to the ARMv7 32 bit? My device is not a 64 bit device! Maybe the updater supports YouTube Revanced for both platforms, but only 64 bit for Music Revanced?

![photo_2022-09-01_20-41-34](https://user-images.githubusercontent.com/16306963/187988935-440454be-3057-4434-b9bf-ccb7b8d77c7d.jpg)

**Comment by rainman74** [comment]
> Are you sure it's not an issue with your device? I can download it without issues.

**Comment by LeddaZ** [comment]
I tried on my ARM 32-bit device and the download is working.
To get logs you can connect the device to your PC, open terminal/command prompt and run `adb logcat > log.txt`, try to download the app, press Ctrl+C and send `log.txt`.
What device is it?

**Comment by rainman74** [comment]
> 
Samsung Galaxy Tab A6

[log.txt](https://github.com/LeddaZ/ReVancedUpdater/files/9477386/log.txt)

**Comment by LeddaZ** [comment]
The issue should be fixed in the latest update

**Comment by rainman74** [comment]
Yes it is fixed in 1.5.0 Thank you very much!
