### ISSUE TITLE
App not installed! But newer MicroG is installed

### ISSUE THREAD

**Issue by rainman74** [LeddaZ/ReVancedUpdater#9]
App not installed! But newer MicroG is installed

![201420962-fd087cf6-8d39-46ed-af83-31aaf1d19065](https://user-images.githubusercontent.com/16306963/201476289-e440b63a-b72c-41d7-ac62-b60c2c2d2687.png)

**Comment by LeddaZ** [comment]
Not applicable anymore with the new microG
